import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/component/nav/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-blue-400 bg-blend-screen">
      <body className={inter.className} >
        <Nav/>
        {children}
        
        </body>
    </html>
  )
}
